baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "STA 210"
theme = "material"
#disqusShortname = ""
# googleAnalytics = ""
paginate = 7
relativeURLs = true
uglyURLs = true
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Dr. Maria Tackett"
  bio = ""
  job = "Assistant Professor of the Practice"
  location = "Duke University"
  gravatarEmail = "maria.tackett@duke.edu"
  # Your profile picture
#  picture = ""
  twitter = "MT_statistics"
 
# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "schedule"
  name = "schedule"
  pre = "<i class=\"material-icons\">calendar_today</i>"
  url = "/schedule.html"
[[menu.main]]
  weight = 3
  identifier = "syllabus"
  name = "Syllabus"
  pre = "<i class='fa fa-check fa-lg'></i>"
  url = "/syllabus.html"

[[menu.main]]
  weight = 4
  identifier = "rstudio"
  name = "RStudio"
  pre = "<i class=\"material-icons\">cloud</i>"
  url = "https://vm-manage.oit.duke.edu/containers"
  
[[menu.main]]
  weight = 5
  identifier = "github"
  name = "GitHub"
  pre = "<i class='fab fa-github fa-lg'></i>"
  url = "https://github.com/sta210-sp20"

[[menu.main]]
  weight = 6
  identifier = "sakai"
  name = "Sakai"
  pre = "<i class=\"material-icons\">school</i>"
  url = "http://sakai.duke.edu"
  
[[menu.main]]
  weight = 7
  identifier = "help"
  name = "Piazza"
  pre = "<i class=\"material-icons\">help</i>"
  url = "https://piazza.com"
  
[[menu.footer]]
  weight = 1
  identifier = "Duke"
  name = "Duke StatSci"
  pre = "<i class=\"button-icon fa fa-2x fa-map-marker\"></i>"
  url = "http://stat.duke.edu/"
[[menu.footer]]
  weight = 2
  name = "RStudio"
  pre = "<i class=\"icon-rlogo\" style=\"font-size:150%\"></i>"
  url = "https://vm-manage.oit.duke.edu/containers"
[[menu.footer]]
  weight = 3
  identifier = "GitHub"
  name = "GitHub"
  pre = "<i class=\"button-icon fa fa-2x fa-github\"></i>"
  url = "https://github.com/sta210-sp20"
[[menu.footer]]

[params]
  dateFormat = "January 2, 2006"
  background = "https://www2.stat.duke.edu/courses/Spring20/sta210.001/img/bikeshare-reg-plots.png"
  favicon = "https://www2.stat.duke.edu/courses/Spring20/sta210.001/img/sta210_sticker_small.png"
